# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: educational.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'educational.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65\x64ucational.proto\x12\x0b\x65\x64ucational\"*\n\x19GetEducationalDataRequest\x12\r\n\x05title\x18\x01 \x01(\t\"b\n\x0f\x45\x64ucationalData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\t\"E\n\x17\x45\x64ucationalDataResponse\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.educational.EducationalData\"X\n\x19\x41\x64\x64\x45\x64ucationalDataRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\"-\n\x1a\x41\x64\x64\x45\x64ucationalDataResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x1c\x44\x65leteEducationalDataRequest\x12\r\n\x05title\x18\x01 \x01(\t\"0\n\x1d\x44\x65leteEducationalDataResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x1cStreamEducationalDataRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xb3\x03\n\x12\x45\x64ucationalService\x12\x62\n\x12GetEducationalData\x12&.educational.GetEducationalDataRequest\x1a$.educational.EducationalDataResponse\x12\x65\n\x12\x41\x64\x64\x45\x64ucationalData\x12&.educational.AddEducationalDataRequest\x1a\'.educational.AddEducationalDataResponse\x12\x62\n\x15StreamEducationalData\x12).educational.StreamEducationalDataRequest\x1a\x1c.educational.EducationalData0\x01\x12n\n\x15\x44\x65leteEducationalData\x12).educational.DeleteEducationalDataRequest\x1a*.educational.DeleteEducationalDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'educational_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEDUCATIONALDATAREQUEST']._serialized_start=34
  _globals['_GETEDUCATIONALDATAREQUEST']._serialized_end=76
  _globals['_EDUCATIONALDATA']._serialized_start=78
  _globals['_EDUCATIONALDATA']._serialized_end=176
  _globals['_EDUCATIONALDATARESPONSE']._serialized_start=178
  _globals['_EDUCATIONALDATARESPONSE']._serialized_end=247
  _globals['_ADDEDUCATIONALDATAREQUEST']._serialized_start=249
  _globals['_ADDEDUCATIONALDATAREQUEST']._serialized_end=337
  _globals['_ADDEDUCATIONALDATARESPONSE']._serialized_start=339
  _globals['_ADDEDUCATIONALDATARESPONSE']._serialized_end=384
  _globals['_DELETEEDUCATIONALDATAREQUEST']._serialized_start=386
  _globals['_DELETEEDUCATIONALDATAREQUEST']._serialized_end=431
  _globals['_DELETEEDUCATIONALDATARESPONSE']._serialized_start=433
  _globals['_DELETEEDUCATIONALDATARESPONSE']._serialized_end=481
  _globals['_STREAMEDUCATIONALDATAREQUEST']._serialized_start=483
  _globals['_STREAMEDUCATIONALDATAREQUEST']._serialized_end=528
  _globals['_EMPTY']._serialized_start=530
  _globals['_EMPTY']._serialized_end=537
  _globals['_EDUCATIONALSERVICE']._serialized_start=540
  _globals['_EDUCATIONALSERVICE']._serialized_end=975
# @@protoc_insertion_point(module_scope)
